import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavigationBar from "../components/NavigationBar";
import SnowfallBackground from "@/components/SnowfallBackground";
import { Toaster } from "sonner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Pranav Joshi",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased bg-background text-foreground`}>
        <SnowfallBackground />

        {/* Site-wide background video */}
        {/* <video
          className="fixed inset-0 w-full h-full object-cover -z-20 motion-reduce:hidden"
          src="/matrix.mp4"
          autoPlay
          muted
          loop
          playsInline
          aria-hidden="true"
        /> */}
        {/* Dark overlay for readability */}
        {/* <div className="fixed inset-0 bg-black/60 -z-10 pointer-events-none" /> */}
        <NavigationBar />
        {children}
        <Toaster position="bottom-right" theme="dark" />
      </body>
    </html>
  );
}
